version: '3.5'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 1s
      timeout: 1s
      retries: 15

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-lerni
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db-data:
