#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint:fix

# Check linting status
if [ $? -eq 0 ]; then
  # If linting passed, proceed with tests and formatting
  npm test || exit 1
  npm run format

  # Stage only the files that were selected for commit
  files=$(git diff --cached --name-only)
  [ -n "$files" ] && git add $files
else
  # If linting failed, print a message and prevent the commit
  echo "Linting failed. Please fix the linting issues before committing."
  exit 1
fi
